### PR TITLE
fix: display 'add a new mint' modal when keyboard is open

### PR DESCRIPTION
**Pull request by andrew-weber**
alt text

### CODE REVIEW

**Comment by andrew-weber** [comment]
whitespace :angry:

**Comment by KKA11010** [comment]
Thanks a lot for the PR! 👍 Its impossible to see what you have done tho so could you please close this and open a new one? I guess your changes will be readable if you run the linter before creating a PR.

**Comment by KKA11010** [comment]
Related to #8

**Review by KKA11010 — CHANGES_REQUESTED** [review]
Please format the file accordingly to the lint options. There are still too many diffs that are useless and don't belong in the git history.

Regarding the linebreaks, I don't think that removing the rule from the .eslintrc is a good approach. We want to keep a consistent format across the project.

I guess you should be able to configure your IDE to use CRLF for this repository. What do you think @BilligsterUser ?

**Comment by KKA11010** [comment]
LGTM.

What about you, @BilligsterUser?

**Review by KKA11010 — APPROVED** [review]

**Review by BilligsterUser — APPROVED** [review]
👍

**Pull request merged**
