### PR TITLE
Update the cashu token QR

### LINKED ISSUE #26: Update the cashu token QR
Add linking: '**cashu:**cashuA...' to the QR so the app can be opened after using an external scanner (IOS camera, android camera or any other scanner)

### PR DESCRIPTION
**Pull request by BilligsterUser**
closes #26

### CODE REVIEW

**Review by KKA11010 — APPROVED** [review]
Looks good but there is one more thing to change before closing this issue.

- [ ] claiming the token after scanning (Maybe needs to check if the scanned value includes the cashu prefix or not)

**Comment by BilligsterUser** [comment]
[export function isCashuToken(token: string) {](https://github.com/cashubtc/eNuts/blob/0cfef2e346db5638b45bbe6fe1f9f4ec1106f04d/src/util/index.ts#L113)

**Comment by BilligsterUser** [comment]
https://github.com/cashubtc/eNuts/pull/32/commits/a6a86e57adb6548b1675271380ce3f882427c513

**Review by KKA11010 — APPROVED** [review]
🥜

**Pull request merged**
