### PR TITLE
Add Thai translation

### PR DESCRIPTION
**Pull request by vazw**
Added translation `th.json` to assets/translations

### CODE REVIEW

**Review by KKA11010 — APPROVED** [review]
Just checked the translation (using chatGPT) and they seem to be accurate and effectively conveys the intended meaning. Thank you for the PR! :1st_place_medal:

**Comment by KKA11010** [comment]
@vazw There are some missing translations. Please see the logs of the following [workflow](https://github.com/cashubtc/eNuts/actions/runs/9031216576/job/24889761499?pr=346#step:7:44)

**Review by KKA11010 — CHANGES_REQUESTED** [review]
@vazw There are some missing translations. Please see the logs of the following [workflow](https://github.com/cashubtc/eNuts/actions/runs/9031216576/job/24889761499?pr=346#step:7:44)

**Comment by vazw** [comment]
> @vazw There are some missing translations. Please see the logs of the following [workflow](https://github.com/cashubtc/eNuts/actions/runs/9031216576/job/24889761499?pr=346#step:7:44)

Alright I'll Re-check it again and made the new commit.

**Comment by vazw** [comment]
Here Added Missing texts and tested. [actions](https://github.com/vazw/eNuts/actions/runs/9061310584/job/24892817573)

**Pull request merged**
