### PR TITLE
Fixed hu strings in #300

### PR DESCRIPTION
**Pull request by viragur**
Reviewed and fixed GPT wordings in new strings.

### CODE REVIEW

**Comment by KKA11010** [comment]
Thank you! 👍

**Comment by KKA11010** [comment]
@viragur can you rebase your branch please? I've just merged the seed PR which results in conflicts in this PR.

**Comment by viragur** [comment]
@KKA11010 I think I have it 👉 👈  can you merge it?

**Comment by KKA11010** [comment]
> @KKA11010 I think I have it 👉 👈 can you merge it?

It is closed. Maybe you want to create a new one?

**Pull request closed without merging**
